version: "3.8"

services:
  freshmart-frontend:
    build: .
    container_name: freshmart-app
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - VITE_APP_TITLE=FreshMart
      - VITE_APP_DESCRIPTION=Grocery Management System
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add your SpringBoot backend here
  # freshmart-backend:
  #   image: your-backend-image:latest
  #   container_name: freshmart-api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=production
  #   restart: unless-stopped

networks:
  default:
    name: freshmart-network
